# Generated by Django 3.0.7 on 2020-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='id',
        ),
        migrations.AlterField(
            model_name='poste',
            name='id_poste',
            field=models.CharField(db_column='id_poste', max_length=20, primary_key=True, serialize=False),
        ),
    ]
