# Generated by Django 3.0.7 on 2020-06-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0002_auto_20200608_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligacao',
            name='id_poste_destino',
            field=models.ForeignKey(blank=True, db_column='id_poste_destino', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='post_destino', to='rede.Poste'),
        ),
        migrations.AlterField(
            model_name='ligacao',
            name='id_poste_origem',
            field=models.ForeignKey(blank=True, db_column='id_poste_origem', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='poste_origem', to='rede.Poste'),
        ),
    ]
