# Generated by Django 3.0.7 on 2020-06-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0003_auto_20200608_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligacao',
            name='id',
        ),
        migrations.AlterField(
            model_name='ligacao',
            name='id_ligacao',
            field=models.CharField(db_column='id_ligacao', max_length=20, primary_key=True, serialize=False),
        ),
    ]
